### ISSUE TITLE
Multiple grave mods 

### ISSUE THREAD

**Issue by GenesisXBD** [TheNimbleNinja/NimbleNinja-Minecraft_Ascension#2]
ive died a few times and each time 2 graves spawn

**Comment by TheNimbleNinja** [comment]
sorry i didnt look at issue tracker didnt think people would post issues are the two graves the one from erebus the bone one and the grave mod?

**Comment by TheNimbleNinja** [comment]
if so i know about this and i think the only way to fix this is by somehow disableing the erebus grave
