### ISSUE TITLE
Topography crashing

### ISSUE THREAD

**Issue by Zalia254** [TheNimbleNinja/NimbleNinja-Minecraft_Ascension#4]
Topography mod is crashing

**Comment by StephJ2Fan** [comment]
Files are not loading. I tried a mining dim world  and it loaded something else

**Comment by StephJ2Fan** [comment]
![Not a Platform in the sky](https://user-images.githubusercontent.com/13186975/66788728-f2adc600-eea5-11e9-8c5e-e90418235314.png)
