### ISSUE TITLE
Missing Textures (alpha 20)

### ISSUE THREAD

**Issue by Vatisco** [TheNimbleNinja/NimbleNinja-Minecraft_Ascension#7]
I've looked through NEI and found multiple broken textures. I found that these textures seem to be missing
1-16x compressed granite
1-16x compressed dust
![image](https://user-images.githubusercontent.com/48506935/183358855-dca1dad4-89e6-4439-9a29-6275389eaa13.png)
Ectoplasm
![image](https://user-images.githubusercontent.com/48506935/183358938-eeb9a787-0f41-49a1-b995-040db0c7d9cb.png)
Twilight forest Twilight Oak, Canopy, Mangrove, Darkwood, Timewood, Transwood, Minewood and Sortingwood doors
![image](https://user-images.githubusercontent.com/48506935/183359105-8dff756d-caf1-4e18-bbb6-320fb5461a2d.png)

There may be more or this may just be a client side issue but I thought I would report it anyway.

**Comment by TheNimbleNinja** [comment]
the reason the dust and granite dont have textures is because i dont know how to give them textures currently and i dont know about those other items
