### ISSUE TITLE
Overlapping volume slider for IC2 (alpha 20)

### ISSUE THREAD

**Issue by Vatisco** [TheNimbleNinja/NimbleNinja-Minecraft_Ascension#8]
From my experience the IC2 volume slider in the Music & sound options is half covering the Footsteps slider, This could be a client side issue or something that is out of the creators control but if it is fixable here it is.
![image](https://user-images.githubusercontent.com/48506935/183359795-4551f78d-0915-459d-9aea-d351e704fb02.png)

**Comment by TheNimbleNinja** [comment]
dont think i can fix that
