### ISSUE TITLE
Problem with item in "Good ol' Currency Mod" (alpha 20)

### ISSUE THREAD

**Issue by Vatisco** [TheNimbleNinja/NimbleNinja-Minecraft_Ascension#9]
There is an item in the Good ol' Currency Mod that has an incorrectly loaded texture and name. Instead of the name it should probably have it is under the name "item.modcurrency:upgrade_0.name"
![image](https://user-images.githubusercontent.com/48506935/183361068-4457be9c-68d6-4ba2-a335-4f34a7384023.png)

**Comment by TheNimbleNinja** [comment]
no idea wat that is
